name: Replace Variable and Upload

on:
  workflow_dispatch:

jobs:
  process-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Production, Staging]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set VAR_VALUE
        run: echo "VAR_VALUE=${{ matrix.environment == 'Production' && vars.PRODUCTION_VAR || vars.STAGING_VAR }}" >> $GITHUB_ENV

      - name: Print VAR_VALUE
        run: echo "VAR_VALUE is $VAR_VALUE"

      - name: Replace and output
        run: sed "s/__variable__/$VAR_VALUE/g" temp.txt > output_${{ matrix.environment }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.environment }}
          path: output_${{ matrix.environment }}.txt
