name: Production – Approve Per Step (2 vars, fail Test once)

on:
  workflow_dispatch:

# Ensure only one job from this workflow runs at a time.
# Even if you approve multiple jobs, the next one will queue until the current finishes.
concurrency:
  group: production-manual-queue
  cancel-in-progress: false

jobs:
  build:
    # Appears as a separate box and waits for Production approval.
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v4

      - name: Ensure temp.txt exists
        run: |
          ls -la
          test -f temp.txt || (echo "temp.txt missing at repo root" && exit 1)

      - name: Build
        run: |
          echo "Building…"
          echo "BUILD_OK" > build.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: build.txt

  test:
    # Independent job: also waits for Production approval.
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v4

      - name: Test (fails on FIRST attempt only)
        run: |
          echo "Running tests… attempt=$GITHUB_RUN_ATTEMPT"
          if [ "${GITHUB_RUN_ATTEMPT}" = "1" ]; then
            echo "Intentionally failing to demo 'Re-run failed jobs'."
            exit 1
          fi
          echo "TESTS_OK" > tests.txt

      - name: Upload test artifact (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs
          path: tests.txt
          if-no-files-found: ignore

  deploy:
    # Independent job: also waits for Production approval.
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v4

      - name: Show Production variables
        run: |
          echo "VARIABLE:  ${{ vars.VARIABLE }}"
          echo "VARIABLE2: ${{ vars.VARIABLE2 }}"

      - name: Ensure temp.txt exists
        run: |
          ls -la
          test -f temp.txt || (echo "temp.txt missing at repo root" && exit 1)

      - name: Deploy (replace placeholders with Production vars)
        run: |
          # Use '|' as sed delimiter so URLs/paths work fine.
          sed -e "s|__variable__|${{ vars.VARIABLE }}|g" \
              -e "s|__variable2__|${{ vars.VARIABLE2 }}|g" \
              temp.txt > output_production.txt
          echo "Output:"
          cat output_production.txt

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-outputs
          path: output_production.txt
