name: Environment Variable Demo

on:
  workflow_dispatch:

env:
  EnvName: ${{ vars.VARIABLE }} # Will resolve from repo variable at the global level

jobs:
  michel:
    runs-on: ubuntu-latest
    environment:
      name: michel # Approval will be requested if set in GitHub UI
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "VARIABLE is: $EnvName"
          echo "Var2 is: ${{ env.EnvName }}"
      - name: Replace and output
        run: sed "s/__variable__/$EnvName/g" temp.txt > output_michel.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-michel
          path: output_michel.txt

  staging:
    runs-on: ubuntu-latest
    needs: michel
    environment:
      name: Staging # Approval will be requested if set in GitHub UI
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "VARIABLE is: $EnvName"
          echo "Var2 is: ${{ env.EnvName }}"
      - name: Replace and output
        run: sed "s/__variable__/$EnvName/g" temp.txt > output_Staging.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-Staging
          path: output_Staging.txt

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: Production # Approval will be requested if set in GitHub UI
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "VARIABLE is: $EnvName"
          echo "Var2 is: ${{ env.EnvName }}"
      - name: Replace and output
        run: sed "s/__variable__/$EnvName/g" temp.txt > output_Production.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-Production
          path: output_Production.txt
