name: Step Selector (Production, 2 vars, fail once)

on:
  workflow_dispatch:
    inputs:
      run_build:
        description: "Run Build step?"
        required: true
        type: boolean
        default: true
      run_test:
        description: "Run Test step? (fails first attempt to demo rerun)"
        required: true
        type: boolean
        default: true
      run_deploy:
        description: "Run Deploy step?"
        required: true
        type: boolean
        default: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment:
      name: Production   # Approval happens here if you set Required reviewers

    steps:
      - uses: actions/checkout@v4

      - name: Show selected inputs
        run: |
          echo "run_build=${{ inputs.run_build }}"
          echo "run_test=${{ inputs.run_test }}"
          echo "run_deploy=${{ inputs.run_deploy }}"
          echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"

      - name: Ensure input file exists (temp.txt)
        run: |
          ls -la
          test -f temp.txt || (echo "temp.txt missing at repo root" && exit 1)

      - name: Build
        if: ${{ inputs.run_build == true }}
        run: |
          echo "Building…"
          echo "BUILD_OK" > build.txt

      - name: Test (fails on first attempt only)
        if: ${{ inputs.run_test == true }}
        run: |
          echo "Running tests… attempt=$GITHUB_RUN_ATTEMPT"
          if [ "${GITHUB_RUN_ATTEMPT}" = "1" ]; then
            echo "Intentionally failing on first attempt to demo 'Rerun failed job'."
            exit 1
          fi
          echo "TESTS_OK" > tests.txt

      - name: Deploy (replace placeholders using Production env vars)
        if: ${{ inputs.run_deploy == true }}
        run: |
          echo "Resolved VARIABLE:  ${{ vars.VARIABLE }}"
          echo "Resolved VARIABLE2: ${{ vars.VARIABLE2 }}"
          # Replace both placeholders. Use '|' delimiter to avoid issues with URLs.
          sed -e "s|__variable__|${{ vars.VARIABLE }}|g" \
              -e "s|__variable2__|${{ vars.VARIABLE2 }}|g" \
              temp.txt > output_production.txt
          echo "Output file:"
          cat output_production.txt

      - name: Upload artifacts (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: production-run
          path: |
            build.txt
            tests.txt
            output_production.txt
          if-no-files-found: ignore
