name: Environment Variable Demo

on:
  workflow_dispatch:

jobs:
  michel:
    runs-on: ubuntu-latest
    environment:
      name: michel
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "VARIABLE (michel) is: $VARIABLE"
          env | grep VARIABLE || true
      - name: Replace and output
        run: |
          sed "s/__variable__/$VARIABLE/g" temp.txt > output_michel.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-michel
          path: output_michel.txt

  staging:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    needs: michel
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "VARIABLE (Staging) is: $VARIABLE"
          env | grep VARIABLE || true
      - name: Replace and output
        run: |
          sed "s/__variable__/$VARIABLE/g" temp.txt > output_Staging.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-Staging
          path: output_Staging.txt

  production:
    runs-on: ubuntu-latest
    environment:
      name: Production
    needs: staging
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "VARIABLE (Production) is: $VARIABLE"
          env | grep VARIABLE || true
      - name: Replace and output
        run: |
          sed "s/__variable__/$VARIABLE/g" temp.txt > output_Production.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-Production
          path: output_Production.txt
