name: Environment Variable Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment?"
        required: true
        default: "michel"
        type: choice
        options:
          - michel
          - Production
          - Staging

# ENV_LABEL should be defined as a repository/environment variable per environment!
env:
  ENV_LABEL: ${{ vars.ENV_LABEL }}

jobs:
  demo:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print injected environment variable
        run: |
          echo "ENV_LABEL (from environment/repo vars) is: $ENV_LABEL"
          env | grep ENV_LABEL || true

      - name: Replace placeholder in file
        run: |
          sed "s/__variable__/$ENV_LABEL/g" temp.txt > output_${{ github.event.inputs.environment }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.event.inputs.environment }}
          path: output_${{ github.event.inputs.environment }}.txt
