name: Replace Variable and Upload

on:
  workflow_dispatch:

jobs:
  process-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Production, Staging]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set VAR_VALUE
        id: set_var
        run: |
          if [ "${{ matrix.environment }}" = "Production" ]; then
            echo "VAR_VALUE=${{ vars.PRODUCTION_VAR }}" >> $GITHUB_ENV
          else
            echo "VAR_VALUE=${{ vars.STAGING_VAR }}" >> $GITHUB_ENV
          fi

      - name: Print environment variables
        run: env

      - name: Read and replace variable in file
        run: |
          echo "VAR_VALUE is: $VAR_VALUE"
          sed "s/__variable__/$VAR_VALUE/g" temp.txt > output_${{ matrix.environment }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.environment }}
          path: output_${{ matrix.environment }}.txt
