name: Environment Variable Demo

on:
  workflow_dispatch:

jobs:
  michel:
    runs-on: ubuntu-latest
    environment:
      name: michel
    steps:
      - uses: actions/checkout@v4

      - name: Show all variables for debug
        run: printenv | sort

      - name: Replace and output
        run: |
          sed "s/__variable__/${{ vars.ENV_LABEL }}/g" temp.txt > output_michel.txt
          echo "Value used: ${{ vars.ENV_LABEL }}"
          cat output_michel.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-michel
          path: output_michel.txt

  staging:
    runs-on: ubuntu-latest
    needs: michel
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v4

      - name: Show all variables for debug
        run: printenv | sort

      - name: Replace and output
        run: |
          sed "s/__variable__/${{ vars.ENV_LABEL }}/g" temp.txt > output_Staging.txt
          echo "Value used: ${{ vars.ENV_LABEL }}"
          cat output_Staging.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-Staging
          path: output_Staging.txt

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v4

      - name: Show all variables for debug
        run: printenv | sort

      - name: Replace and output
        run: |
          sed "s/__variable__/${{ vars.ENV_LABEL }}/g" temp.txt > output_Production.txt
          echo "Value used: ${{ vars.ENV_LABEL }}"
          cat output_Production.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-Production
          path: output_Production.txt
