name: Environment Variable Demo

on:
  workflow_dispatch:

jobs:
  michel:
    runs-on: ubuntu-latest
    environment:
      name: michel
    env:
      ENV_LABEL:  ${{ vars.VARIABLE }}   # from michel environment
      ENV_LABEL2: ${{ vars.VARIABLE2 }}  # from michel environment
    steps:
      - uses: actions/checkout@v4

      - name: Show values (debug)
        run: |
          echo "ENV_LABEL:  ${{ env.ENV_LABEL }}"
          echo "ENV_LABEL2: ${{ env.ENV_LABEL2 }}"

      - name: Replace placeholders and output
        run: |
          sed -e "s|__variable__|${{ env.ENV_LABEL }}|g" \
              -e "s|__variable2__|${{ env.ENV_LABEL2 }}|g" \
              temp.txt > output_michel.txt

      - uses: actions/upload-artifact@v4
        with:
          name: output-michel
          path: output_michel.txt

  staging:
    runs-on: ubuntu-latest
    needs: michel
    environment:
      name: Staging
    env:
      ENV_LABEL:  ${{ vars.VARIABLE }}   # from Staging environment
      ENV_LABEL2: ${{ vars.VARIABLE2 }}  # from Staging environment
    steps:
      - uses: actions/checkout@v4

      - name: Show values (debug)
        run: |
          echo "ENV_LABEL:  ${{ env.ENV_LABEL }}"
          echo "ENV_LABEL2: ${{ env.ENV_LABEL2 }}"

      - name: Replace placeholders and output
        run: |
          sed -e "s|__variable__|${{ env.ENV_LABEL }}|g" \
              -e "s|__variable2__|${{ env.ENV_LABEL2 }}|g" \
              temp.txt > output_Staging.txt

      - uses: actions/upload-artifact@v4
        with:
          name: output-Staging
          path: output_Staging.txt

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: Production
    env:
      ENV_LABEL:  ${{ vars.VARIABLE }}   # from Production environment
      ENV_LABEL2: ${{ vars.VARIABLE2 }}  # from Production environment
    steps:
      - uses: actions/checkout@v4

      - name: Show values (debug)
        run: |
          echo "ENV_LABEL:  ${{ env.ENV_LABEL }}"
          echo "ENV_LABEL2: ${{ env.ENV_LABEL2 }}"

      - name: Replace placeholders and output
        run: |
          sed -e "s|__variable__|${{ env.ENV_LABEL }}|g" \
              -e "s|__variable2__|${{ env.ENV_LABEL2 }}|g" \
              temp.txt > output_Production.txt

      - uses: actions/upload-artifact@v4
        with:
          name: output-Production
          path: output_Production.txt
