name: PROD (call next)

on:
  workflow_dispatch:

jobs:
  print_values:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout
        run: |
          echo "The secret is:"+"${{ secrets.TEXT_VAR }}"
          echo "The var is:"+"${{ vars.TEST_VAR }}"
  call-workflow:
    uses: ./.github/workflows/next.yml
    secrets:
      inherit
    with:
      environment: PROD
  call-workflow-org:
    uses: ./.github/workflows/next.yml
    secrets:
      inherit
    with:
      environment: michel
