name: PROD (call next)

on:
  workflow_dispatch:

jobs:
  print_values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "The secret is:"+"${{ secrets.TEXT_VAR }}"
          echo "The var is:"+"${{ env.TEST_VAR }}"
  call-workflow:
    uses: ./.github/workflows/next.yml@nimrod_test
    secrets:
      inherit
    with:
      file_path: temp.txt
