name: Replace Variable and Upload (Single Env)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'Production'
        type: choice
        options:
          - Production
          - Staging

jobs:
  process-env:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print injected VARIABLE
        run: |
          echo "VARIABLE is: $VARIABLE"
          env

      - name: Replace and output
        run: |
          sed "s/__variable__/$VARIABLE/g" temp.txt > output_${{ github.event.inputs.environment }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.event.inputs.environment }}
          path: output_${{ github.event.inputs.environment }}.txt
