name: Environment Variable Demo

on:
  workflow_dispatch:

jobs:
  michel:
    runs-on: ubuntu-latest
    environment:
      name: michel
    env:
      ENV_LABEL: ${{ vars.ENV_LABEL }}    # <--- This picks up michel's env var
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "ENV_LABEL (michel) is: ${{ env.ENV_LABEL }}"
          env | grep ENV_LABEL || true
      - name: Replace and output
        run: |
          sed "s/__variable__/${{ env.ENV_LABEL }}/g" temp.txt > output_michel.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-michel
          path: output_michel.txt

  staging:
    runs-on: ubuntu-latest
    needs: michel
    environment:
      name: Staging
    env:
      ENV_LABEL: ${{ vars.ENV_LABEL }}    # <--- This picks up Staging's env var
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "ENV_LABEL (Staging) is: ${{ env.ENV_LABEL }}"
          env | grep ENV_LABEL || true
      - name: Replace and output
        run: |
          sed "s/__variable__/${{ env.ENV_LABEL }}/g" temp.txt > output_Staging.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-Staging
          path: output_Staging.txt

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: Production
    env:
      ENV_LABEL: ${{ vars.ENV_LABEL }}    # <--- This picks up Production's env var
    steps:
      - uses: actions/checkout@v4
      - name: Print injected environment variable
        run: |
          echo "ENV_LABEL (Production) is: ${{ env.ENV_LABEL }}"
          env | grep ENV_LABEL || true
      - name: Replace and output
        run: |
          sed "s/__variable__/${{ env.ENV_LABEL }}/g" temp.txt > output_Production.txt
      - uses: actions/upload-artifact@v4
        with:
          name: output-Production
          path: output_Production.txt
