name: Environment Variable Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment?"
        required: true
        default: "Production"
        type: choice
        options:
          - Production
          - Staging

jobs:
  demo:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Print injected environment variable
        run: |
          echo "VARIABLE is: $VARIABLE"
          env | grep VARIABLE || true

      - name: Replace and output
        run: |
          sed "s/__variable__/$VARIABLE/g" temp.txt > output_${{ github.event.inputs.environment }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.event.inputs.environment }}
          path: output_${{ github.event.inputs.environment }}.txt
