name: Environment Variable Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment?"
        required: true
        default: "michel"
        type: choice
        options:
          - michel
          - Production
          - Staging

env:
  koko: ${{ vars.ENVNAME }} # ENVNAME must exist as a repo or environment variable

jobs:
  demo:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Print injected environment variable
        run: |
          echo "VARIABLE is: $koko"
          echo "Var2 is: ${{ env.koko }}"
          env | grep koko || true

      - name: Replace and output
        run: |
          sed "s/__variable__/$koko/g" temp.txt > output_${{ github.event.inputs.environment }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.event.inputs.environment }}
          path: output_${{ github.event.inputs.environment }}.txt
