name: next (forwards to nextnext)

on:
  workflow_call:
    inputs:
      file_path:
        type: string
        required: true
    secrets:
      TEXT_VAR:
        required: true

jobs:
  print_values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "The secret is:"+"${{ secrets.TEXT_VAR }}"
          echo "The var is:"+"${{ env.TEST_VAR }}"
  call_nextnext:
    uses: ./.github/workflows/nextnext.yml@nimrod_test
    secrets:
      inherit
    with:
      file_path: ${{ inputs.file_path }}
