name: nextnext (apply and commit)

on:
  workflow_call:
    inputs:
      file_path:
        type: string
        required: true
    secrets:
      TEXT_VAR:
        required: true

permissions:
  contents: write   # needed to push changes

jobs:
  print_values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "The var is:"+"${{ secrets.TEXT_VAR }}"
          echo "The var is:"+"${{ env.TEST_VAR }}"
